name: ci
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        ghc: ['8.10', '9.0']
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2'
    - name: Update cabal package database
      run: |
        cabal update
        cabal freeze
    - uses: actions/cache@v2.1.6
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-
    - name: make
      run: |
        make
    - name: Test
      run: |
        make test
    - name: SDist
      run: |
        make sdist
